// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async authLoginWithPassword(request: PasswordLoginRequestDto) : Promise<Result<PasswordLoginResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_login_with_password", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authSendEmailLogin(request: SendEmailLoginRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_send_email_login", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authVerifyEmailToken(request: VerifyEmailTokenRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_verify_email_token", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRestoreState(request: RestoreAuthStateRequestDto) : Promise<Result<RestoreAuthStateResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_restore_state", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authLogout(request: LogoutRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_logout", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authSendVerificationEmail(request: SendVerificationEmailRequestDto) : Promise<Result<SendVerificationEmailResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_send_verification_email", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRegisterFinish(request: RegisterFinishRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_register_finish", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGetAppConfig() : Promise<Result<AppConfigDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get_app_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configUpdateAppConfig(request: UpdateAppConfigRequest) : Promise<Result<AppConfigDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_update_app_config", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configCheckTextInjectionPermission() : Promise<boolean> {
    return await TAURI_INVOKE("config_check_text_injection_permission");
},
async desktopOpenMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("desktop_open_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFolders() : Promise<Result<FolderDto[], ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(request: CreateFolderRequest) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFolder(request: RenameFolderRequest) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_folder", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFolder(request: DeleteFolderRequest) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultSyncNow(request: SyncNowRequestDto) : Promise<Result<SyncStatusResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_sync_now", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultSyncStatus(request: SyncStatusRequestDto) : Promise<Result<SyncStatusResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_sync_status", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultSyncCheckRevision(request: SyncStatusRequestDto) : Promise<Result<SyncStatusResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_sync_check_revision", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current unlock state
 */
async getUnlockState(request: GetUnlockStateRequestDto) : Promise<Result<UnlockStateResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_unlock_state", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually refresh the session
 */
async refreshSession(request: RefreshSessionRequestDto) : Promise<Result<RefreshSessionResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_session", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasLocalUnlockData() : Promise<Result<boolean, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_local_unlock_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultGetBiometricStatus() : Promise<Result<VaultBiometricStatusResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_get_biometric_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultGetPinStatus() : Promise<Result<VaultPinStatusResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_get_pin_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultCanUnlockWithBiometric() : Promise<Result<boolean, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_can_unlock_with_biometric") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultUnlock(request: VaultUnlockRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_unlock", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultEnablePinUnlock(request: VaultEnablePinUnlockRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_enable_pin_unlock", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultDisablePinUnlock(request: VaultDisablePinUnlockRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_disable_pin_unlock", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultEnableBiometricUnlock(request: VaultEnableBiometricUnlockRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_enable_biometric_unlock", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultDisableBiometricUnlock(request: VaultDisableBiometricUnlockRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_disable_biometric_unlock", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultLock(request: VaultLockRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_lock", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultGetViewData() : Promise<Result<VaultViewDataResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_get_view_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultListCiphers() : Promise<Result<VaultCipherItemDto[], ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_list_ciphers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultGetCipherDetail(request: VaultCipherDetailRequestDto) : Promise<Result<VaultCipherDetailResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_get_cipher_detail", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultCopyCipherField(request: VaultCopyCipherFieldRequestDto) : Promise<Result<VaultCopyCipherFieldResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_copy_cipher_field", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute autofill with the stored value
 * This should be called by frontend after spotlight is hidden
 */
async vaultExecuteAutofill(request: VaultExecuteAutofillRequestDto) : Promise<Result<VaultExecuteAutofillResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_execute_autofill", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultGetCipherTotpCode(request: VaultCipherTotpCodeRequestDto) : Promise<Result<VaultCipherTotpCodeResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_get_cipher_totp_code", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets an icon for the given hostname.
 * 
 * # Arguments
 * * `hostname` - The hostname (e.g., "google.com")
 * 
 * # Returns
 * * `Ok(Some(base64))` - Icon data as base64-encoded PNG
 * * `Ok(None)` - Icon not available
 * * `Err(...)` - Error during operation
 */
async getIcon(hostname: string) : Promise<Result<string | null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_icon", { hostname }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clears the icon cache.
 * 
 * # Returns
 * * `Ok(())` - Cache cleared successfully
 * * `Err(...)` - Error during operation
 */
async clearIconCache() : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_icon_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCipher(request: CreateCipherRequestDto) : Promise<Result<CipherMutationResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_cipher", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCipher(request: UpdateCipherRequestDto) : Promise<Result<CipherMutationResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_cipher", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCipher(request: DeleteCipherRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cipher", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async softDeleteCipher(request: SoftDeleteCipherRequestDto) : Promise<Result<CipherMutationResponseDto, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("soft_delete_cipher", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreCipher(request: RestoreCipherRequestDto) : Promise<Result<null, ErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_cipher", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
cipherCreated: CipherCreated,
cipherDeleted: CipherDeleted,
cipherUpdated: CipherUpdated,
unlockStateChanged: UnlockStateChanged,
vaultFoldersSynced: VaultFoldersSynced,
vaultSyncAuthRequired: VaultSyncAuthRequired,
vaultSyncFailed: VaultSyncFailed,
vaultSyncLoggedOut: VaultSyncLoggedOut,
vaultSyncStarted: VaultSyncStarted,
vaultSyncSucceeded: VaultSyncSucceeded
}>({
cipherCreated: "cipher:created",
cipherDeleted: "cipher:deleted",
cipherUpdated: "cipher:updated",
unlockStateChanged: "unlock-state:changed",
vaultFoldersSynced: "vault-folders:synced",
vaultSyncAuthRequired: "vault-sync:auth-required",
vaultSyncFailed: "vault-sync:failed",
vaultSyncLoggedOut: "vault-sync:logged-out",
vaultSyncStarted: "vault-sync:started",
vaultSyncSucceeded: "vault-sync:succeeded"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Account context information (non-sensitive)
 */
export type AccountContextDto = { accountId: string; email: string; baseUrl: string }
export type AppConfigDto = { deviceIdentifier: string; allowInvalidCerts: boolean; syncPollIntervalSeconds: number; locale: string; launchOnLogin: boolean; showWebsiteIcon: boolean; quickAccessShortcut: string; lockShortcut: string; requireMasterPasswordInterval: string; lockOnSleep: boolean; idleAutoLockDelay: string; clipboardClearDelay: string; spotlightAutofill: boolean }
/**
 * Cipher attachment data
 */
export type CipherAttachment<S> = { id: string; 
/**
 * Plain text field - not encrypted
 */
key?: string | null; file_name: { inner: string | null }; 
/**
 * Plain text field - not encrypted
 */
size?: string | null; 
/**
 * Plain text field - not encrypted
 */
size_name?: string | null; 
/**
 * Plain text field - not encrypted
 */
url?: string | null; object?: string | null }
/**
 * Cipher card data
 */
export type CipherCard<S> = { cardholder_name: { inner: string | null }; brand: { inner: string | null }; number: { inner: string | null }; exp_month: { inner: string | null }; exp_year: { inner: string | null }; code: { inner: string | null } }
export type CipherCreated = { accountId: string; cipherId: string }
/**
 * Cipher data (legacy structure containing all fields)
 */
export type CipherData<S> = { name: { inner: string | null }; notes: { inner: string | null }; fields?: CipherField<S>[]; password_history?: CipherPasswordHistory<S>[]; uri: { inner: string | null }; uris?: CipherLoginUri<S>[]; username: { inner: string | null }; password: { inner: string | null }; 
/**
 * Plain text field - not encrypted
 */
password_revision_date?: string | null; totp: { inner: string | null }; autofill_on_page_load?: boolean | null; fido2_credentials?: CipherLoginFido2Credential<S>[]; type?: number | null; cardholder_name: { inner: string | null }; brand: { inner: string | null }; number: { inner: string | null }; exp_month: { inner: string | null }; exp_year: { inner: string | null }; code: { inner: string | null }; title: { inner: string | null }; first_name: { inner: string | null }; middle_name: { inner: string | null }; last_name: { inner: string | null }; address1: { inner: string | null }; address2: { inner: string | null }; address3: { inner: string | null }; city: { inner: string | null }; state: { inner: string | null }; postal_code: { inner: string | null }; country: { inner: string | null }; company: { inner: string | null }; email: { inner: string | null }; phone: { inner: string | null }; ssn: { inner: string | null }; passport_number: { inner: string | null }; license_number: { inner: string | null }; private_key: { inner: string | null }; public_key: { inner: string | null }; key_fingerprint: { inner: string | null } }
export type CipherDeleted = { accountId: string; cipherId: string }
/**
 * Cipher custom field
 */
export type CipherField<S> = { name: { inner: string | null }; value: { inner: string | null }; type?: number | null; linked_id?: number | null }
/**
 * Cipher identity data
 */
export type CipherIdentity<S> = { title: { inner: string | null }; first_name: { inner: string | null }; middle_name: { inner: string | null }; last_name: { inner: string | null }; address1: { inner: string | null }; address2: { inner: string | null }; address3: { inner: string | null }; city: { inner: string | null }; state: { inner: string | null }; postal_code: { inner: string | null }; country: { inner: string | null }; company: { inner: string | null }; email: { inner: string | null }; phone: { inner: string | null }; ssn: { inner: string | null }; username: { inner: string | null }; passport_number: { inner: string | null }; license_number: { inner: string | null } }
/**
 * Cipher login data
 */
export type CipherLogin<S> = { uri: { inner: string | null }; uris?: CipherLoginUri<S>[]; username: { inner: string | null }; password: { inner: string | null }; 
/**
 * Plain text field - not encrypted
 */
password_revision_date?: string | null; totp: { inner: string | null }; autofill_on_page_load?: boolean | null; fido2_credentials?: CipherLoginFido2Credential<S>[] }
/**
 * Cipher login FIDO2 credential
 */
export type CipherLoginFido2Credential<S> = { credential_id: { inner: string | null }; key_type: { inner: string | null }; key_algorithm: { inner: string | null }; key_curve: { inner: string | null }; key_value: { inner: string | null }; rp_id: { inner: string | null }; rp_name: { inner: string | null }; counter: { inner: string | null }; user_handle: { inner: string | null }; user_name: { inner: string | null }; user_display_name: { inner: string | null }; discoverable: { inner: string | null }; creation_date: { inner: string | null } }
/**
 * Cipher login URI
 */
export type CipherLoginUri<S> = { uri: { inner: string | null }; match?: number | null; 
/**
 * Plain text field - not encrypted
 */
uri_checksum?: string | null }
export type CipherMutationResponseDto = { cipherId: string; revisionDate: string }
/**
 * Cipher password history entry
 */
export type CipherPasswordHistory<S> = { password: { inner: string | null }; 
/**
 * Plain text field - not encrypted
 */
last_used_date?: string | null }
/**
 * Cipher permissions (no encrypted fields)
 */
export type CipherPermissions = { delete?: boolean | null; restore?: boolean | null }
/**
 * Cipher secure note data (no encrypted fields)
 */
export type CipherSecureNote = { type?: number | null }
/**
 * Cipher SSH key data
 */
export type CipherSshKey<S> = { private_key: { inner: string | null }; public_key: { inner: string | null }; key_fingerprint: { inner: string | null } }
export type CipherUpdated = { accountId: string; cipherId: string }
export type CreateCipherRequestDto = { cipher: SyncCipher }
export type CreateFolderRequest = { name: string }
/**
 * Marker type for decrypted cipher state
 */
export type Decrypted = null
export type DeleteCipherRequestDto = { cipherId: string }
export type DeleteFolderRequest = { folderId: string }
export type ErrorPayload = { code: string; message: string; details?: JsonValue | null; timestamp: number; severity: ErrorSeverity }
export type ErrorSeverity = "info" | "warning" | "error" | "fatal"
export type FolderDto = { id: string; name: string }
/**
 * Request to get unlock state
 */
export type GetUnlockStateRequestDto = Record<string, never>
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LogoutRequestDto = Record<string, never>
export type MasterPasswordPolicyDto = { minComplexity: number | null; minLength: number | null; requireLower: boolean; requireUpper: boolean; requireNumbers: boolean; requireSpecial: boolean; enforceOnLogin: boolean; object: string | null }
export type PasswordLoginRequestDto = { baseUrl: string; email: string; masterPassword: string; twoFactorProvider: number | null; twoFactorToken: string | null; twoFactorRemember: boolean | null; authrequest: string | null }
export type PasswordLoginResponseDto = ({ status: "authenticated" } & SessionResponseDto) | ({ status: "twoFactorRequired" } & TwoFactorChallengeDto)
/**
 * Request to refresh session
 */
export type RefreshSessionRequestDto = Record<string, never>
/**
 * Response from refresh session
 */
export type RefreshSessionResponseDto = { success: boolean; isSessionValid: boolean }
export type RegisterFinishRequestDto = { baseUrl: string; email: string; name: string; masterPassword: string; masterPasswordHint: string | null; token: string; kdf: number; kdfIterations: number; kdfMemory: number | null; kdfParallelism: number | null }
export type RenameFolderRequest = { folderId: string; newName: string }
export type RestoreAuthStateRequestDto = Record<string, never>
export type RestoreAuthStateResponseDto = { status: RestoreAuthStateStatusDto; accountId: string | null; baseUrl: string | null; email: string | null }
export type RestoreAuthStateStatusDto = "needsLogin" | "locked" | "authenticated"
export type RestoreCipherRequestDto = { cipherId: string }
export type SendEmailLoginRequestDto = { baseUrl: string; email: string | null; masterPassword: string | null; authRequestId: string | null; authRequestAccessCode: string | null }
export type SendVerificationEmailRequestDto = { baseUrl: string; email: string; name: string | null }
export type SendVerificationEmailResponseDto = { outcome: "disabled"; message: string } | { outcome: "emailVerificationRequired" } | { outcome: "directRegistration"; token: string }
/**
 * Session context information
 */
export type SessionContextDto = { 
/**
 * Whether the session is valid (not expired)
 */
isValid: boolean; 
/**
 * Whether the session is expiring soon (within grace period)
 */
isExpiringSoon: boolean }
export type SessionResponseDto = { accessToken: string; refreshToken: string | null; expiresIn: number; tokenType: string; scope: string | null; key: string | null; privateKey: string | null; kdf: number | null; kdfIterations: number | null; kdfMemory: number | null; kdfParallelism: number | null; twoFactorToken: string | null }
export type SoftDeleteCipherRequestDto = { cipherId: string }
export type SyncAttachment = { id: string; key: string | null; file_name: string | null; size: string | null; size_name: string | null; url: string | null; object: string | null }
export type SyncCipher = { id: string; organization_id: string | null; folder_id: string | null; type: number | null; name: string | null; notes: string | null; key: string | null; favorite: boolean | null; edit: boolean | null; view_password: boolean | null; organization_use_totp: boolean | null; creation_date: string | null; revision_date: string | null; deleted_date: string | null; archived_date: string | null; reprompt: number | null; permissions: SyncCipherPermissions | null; object: string | null; fields: SyncCipherField[]; password_history: SyncCipherPasswordHistory[]; collection_ids: string[]; data: SyncCipherData | null; login: SyncCipherLogin | null; secure_note: SyncCipherSecureNote | null; card: SyncCipherCard | null; identity: SyncCipherIdentity | null; ssh_key: SyncCipherSshKey | null; attachments: SyncAttachment[] }
export type SyncCipherCard = { cardholder_name: string | null; brand: string | null; number: string | null; exp_month: string | null; exp_year: string | null; code: string | null }
export type SyncCipherData = { name: string | null; notes: string | null; fields: SyncCipherField[]; password_history: SyncCipherPasswordHistory[]; uri: string | null; uris: SyncCipherLoginUri[]; username: string | null; password: string | null; password_revision_date: string | null; totp: string | null; autofill_on_page_load: boolean | null; fido2_credentials: SyncCipherLoginFido2Credential[]; type: number | null; cardholder_name: string | null; brand: string | null; number: string | null; exp_month: string | null; exp_year: string | null; code: string | null; title: string | null; first_name: string | null; middle_name: string | null; last_name: string | null; address1: string | null; address2: string | null; address3: string | null; city: string | null; state: string | null; postal_code: string | null; country: string | null; company: string | null; email: string | null; phone: string | null; ssn: string | null; passport_number: string | null; license_number: string | null; private_key: string | null; public_key: string | null; key_fingerprint: string | null }
export type SyncCipherField = { name: string | null; value: string | null; type: number | null; linked_id: number | null }
export type SyncCipherIdentity = { title: string | null; first_name: string | null; middle_name: string | null; last_name: string | null; address1: string | null; address2: string | null; address3: string | null; city: string | null; state: string | null; postal_code: string | null; country: string | null; company: string | null; email: string | null; phone: string | null; ssn: string | null; username: string | null; passport_number: string | null; license_number: string | null }
export type SyncCipherLogin = { uri: string | null; uris: SyncCipherLoginUri[]; username: string | null; password: string | null; password_revision_date: string | null; totp: string | null; autofill_on_page_load: boolean | null; fido2_credentials: SyncCipherLoginFido2Credential[] }
export type SyncCipherLoginFido2Credential = { credential_id: string | null; key_type: string | null; key_algorithm: string | null; key_curve: string | null; key_value: string | null; rp_id: string | null; rp_name: string | null; counter: string | null; user_handle: string | null; user_name: string | null; user_display_name: string | null; discoverable: string | null; creation_date: string | null }
export type SyncCipherLoginUri = { uri: string | null; match: number | null; uri_checksum: string | null }
export type SyncCipherPasswordHistory = { password: string | null; last_used_date: string | null }
export type SyncCipherPermissions = { delete: boolean | null; restore: boolean | null }
export type SyncCipherSecureNote = { type: number | null }
export type SyncCipherSshKey = { private_key: string | null; public_key: string | null; key_fingerprint: string | null }
export type SyncCountsDto = { folders: number; collections: number; policies: number; ciphers: number; sends: number }
export type SyncMetricsDto = { windowSize: number; sampleCount: number; successCount: number; failureCount: number; failureRate: number; lastDurationMs: number | null; averageDurationMs: number | null; lastCounts: SyncCountsDto | null; averageCounts: SyncCountsDto | null }
export type SyncNowRequestDto = { excludeDomains: boolean | null }
export type SyncStateDto = "idle" | "running" | "succeeded" | "degraded" | "failed"
export type SyncStatusRequestDto = Record<string, never>
export type SyncStatusResponseDto = { accountId: string; baseUrl: string | null; state: SyncStateDto; wsStatus: WsStatusDto; lastRevisionMs: string | null; lastSyncAtMs: string | null; lastError: string | null; counts: SyncCountsDto; metrics: SyncMetricsDto | null }
export type TwoFactorChallengeDto = { error: string | null; errorDescription: string | null; providers: string[]; providers2: Partial<{ [key in string]: TwoFactorProviderHintDto | null }> | null; masterPasswordPolicy: MasterPasswordPolicyDto | null }
export type TwoFactorProviderHintDto = { host: string | null; signature: string | null; authUrl: string | null; nfc: boolean | null; email: string | null; challenge: string | null; timeout: number | null; rpId: string | null; allowCredentials: WebauthnAllowCredentialDto[]; userVerification: string | null; extensions: WebauthnRequestExtensionsDto | null }
/**
 * Unlock method used
 */
export type UnlockMethodDto = { type: "masterPassword" } | { type: "pin" } | { type: "biometric" }
/**
 * Tauri event for unlock state changes
 */
export type UnlockStateChanged = { event: UnlockStateEvent }
/**
 * Event emitted when unlock state changes
 */
export type UnlockStateEvent = { oldStatus: UnlockStatusDto; newStatus: UnlockStatusDto; hasKeyMaterial: boolean; accountId: string | null }
/**
 * Complete unlock state response
 */
export type UnlockStateResponseDto = { status: UnlockStatusDto; account: AccountContextDto | null; session: SessionContextDto | null; 
/**
 * Whether vault keys are available in memory
 */
hasKeyMaterial: boolean; 
/**
 * The method used to unlock (if currently unlocked)
 */
unlockMethod: UnlockMethodDto | null }
/**
 * Current unlock status
 */
export type UnlockStatusDto = 
/**
 * Vault is locked, no session or keys available
 */
"locked" | 
/**
 * Vault is unlocked but API session has expired
 */
"vaultUnlockedSessionExpired" | 
/**
 * Both vault and API session are valid
 */
"fullyUnlocked" | 
/**
 * Unlock operation is in progress
 */
"unlocking"
export type UpdateAppConfigRequest = { locale?: string | null; launchOnLogin?: boolean | null; showWebsiteIcon?: boolean | null; quickAccessShortcut?: string | null; lockShortcut?: string | null; requireMasterPasswordInterval?: string | null; lockOnSleep?: boolean | null; idleAutoLockDelay?: string | null; clipboardClearDelay?: string | null; spotlightAutofill?: boolean | null }
export type UpdateCipherRequestDto = { cipherId: string; cipher: SyncCipher }
export type VaultBiometricStatusResponseDto = { supported: boolean; enabled: boolean }
/**
 * Vault cipher detail DTO using domain type with flattened fields
 */
export type VaultCipherDetailDto = 
/**
 * Flatten all Cipher<Decrypted> fields to the top level
 */
({ id: string; organization_id?: string | null; folder_id?: string | null; type?: number | null; name: { inner: string | null }; notes: { inner: string | null }; 
/**
 * Cipher key - stored as encrypted string, should not be decrypted like regular fields
 */
key?: string | null; favorite?: boolean | null; edit?: boolean | null; view_password?: boolean | null; organization_use_totp?: boolean | null; creation_date?: string | null; revision_date?: string | null; deleted_date?: string | null; archived_date?: string | null; reprompt?: number | null; permissions?: CipherPermissions | null; object?: string | null; fields?: CipherField<Decrypted>[]; password_history?: CipherPasswordHistory<Decrypted>[]; collection_ids?: string[]; data?: CipherData<Decrypted> | null; login?: CipherLogin<Decrypted> | null; secure_note?: CipherSecureNote | null; card?: CipherCard<Decrypted> | null; identity?: CipherIdentity<Decrypted> | null; ssh_key?: CipherSshKey<Decrypted> | null; attachments?: CipherAttachment<Decrypted>[] }) & { 
/**
 * Computed field: whether the cipher has TOTP configured
 */
hasTotp: boolean }
export type VaultCipherDetailRequestDto = { cipherId: string }
export type VaultCipherDetailResponseDto = { accountId: string; cipher: VaultCipherDetailDto }
export type VaultCipherItemDto = { id: string; folderId: string | null; organizationId: string | null; type: number | null; name: string | null; username: string | null; uris: string[]; favorite: boolean | null; creationDate: string | null; revisionDate: string | null; deletedDate: string | null; attachmentCount: number }
export type VaultCipherTotpCodeRequestDto = { cipherId: string }
export type VaultCipherTotpCodeResponseDto = { code: string; periodSeconds: number; remainingSeconds: number; expiresAtMs: number }
export type VaultCopyCipherFieldRequestDto = { cipherId: string; field: VaultCopyFieldDto; clearAfterMs: number | null }
export type VaultCopyCipherFieldResponseDto = { copied: boolean; clearAfterMs: number | null; autofillPerformed: boolean; 
/**
 * The copied value - will be set if autofill is enabled so frontend can trigger autofill after hiding spotlight
 */
value: string | null }
export type VaultCopyFieldDto = "username" | "password" | "totp" | "notes" | { customField: { index: number } } | { uri: { index: number } } | "cardNumber" | "cardCode" | "email" | "phone" | "sshPrivateKey" | "sshPublicKey"
export type VaultDisableBiometricUnlockRequestDto = Record<string, never>
export type VaultDisablePinUnlockRequestDto = Record<string, never>
export type VaultEnableBiometricUnlockRequestDto = Record<string, never>
export type VaultEnablePinUnlockRequestDto = { pin: string; lockType: VaultPinLockTypeDto }
export type VaultExecuteAutofillRequestDto = { value: string }
export type VaultExecuteAutofillResponseDto = { success: boolean }
export type VaultFolderItemDto = { id: string; name: string | null }
export type VaultFoldersSynced = { accountId: string; folderCount: number }
export type VaultLockRequestDto = Record<string, never>
export type VaultPinLockTypeDto = "disabled" | "ephemeral" | "persistent"
export type VaultPinStatusResponseDto = { supported: boolean; enabled: boolean; lockType: VaultPinLockTypeDto }
export type VaultSyncAuthRequired = { accountId: string; status: number; message: string }
export type VaultSyncFailed = { accountId: string; code: string; message: string }
export type VaultSyncLoggedOut = { accountId: string; reason: string }
export type VaultSyncStarted = { accountId: string }
export type VaultSyncSucceeded = { accountId: string; status: SyncStatusResponseDto }
export type VaultUnlockMethodDto = { type: "masterPassword"; password: string } | { type: "pin"; pin: string } | { type: "biometric" }
export type VaultUnlockRequestDto = { method: VaultUnlockMethodDto }
export type VaultViewDataResponseDto = { accountId: string; syncStatus: SyncStatusResponseDto; folders: VaultFolderItemDto[]; ciphers: VaultCipherItemDto[]; totalCiphers: number }
export type VerifyEmailTokenRequestDto = { baseUrl: string; userId: string; token: string }
export type WebauthnAllowCredentialDto = { type: string | null; id: string | null; transports: string[] }
export type WebauthnRequestExtensionsDto = { appid: string | null }
export type WsStatusDto = "unknown" | "connected" | "disconnected"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
