// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async authPrelogin(request: PreloginRequestDto) : Promise<Result<PreloginResponseDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_prelogin", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authLoginWithPassword(request: PasswordLoginRequestDto) : Promise<Result<PasswordLoginResponseDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_login_with_password", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRefreshToken(request: RefreshTokenRequestDto) : Promise<Result<SessionResponseDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_refresh_token", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authSendEmailLogin(request: SendEmailLoginRequestDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_send_email_login", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authVerifyEmailToken(request: VerifyEmailTokenRequestDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_verify_email_token", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultSyncNow(request: SyncNowRequestDto) : Promise<Result<SyncStatusResponseDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_sync_now", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultSyncStatus(request: SyncStatusRequestDto) : Promise<Result<SyncStatusResponseDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_sync_status", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
vaultSyncFailed: VaultSyncFailed,
vaultSyncStarted: VaultSyncStarted,
vaultSyncSucceeded: VaultSyncSucceeded
}>({
vaultSyncFailed: "vault-sync:failed",
vaultSyncStarted: "vault-sync:started",
vaultSyncSucceeded: "vault-sync:succeeded"
})

/** user-defined constants **/



/** user-defined types **/

export type MasterPasswordPolicyDto = { minComplexity: number | null; minLength: number | null; requireLower: boolean; requireUpper: boolean; requireNumbers: boolean; requireSpecial: boolean; enforceOnLogin: boolean; object: string | null }
export type PasswordLoginRequestDto = { baseUrl: string; username: string; password: string; twoFactorProvider: number | null; twoFactorToken: string | null; twoFactorRemember: boolean | null; authrequest: string | null }
export type PasswordLoginResponseDto = ({ status: "authenticated" } & SessionResponseDto) | ({ status: "twoFactorRequired" } & TwoFactorChallengeDto)
export type PreloginRequestDto = { baseUrl: string; email: string }
export type PreloginResponseDto = { kdf: number; kdfIterations: number; kdfMemory: number | null; kdfParallelism: number | null }
export type RefreshTokenRequestDto = { baseUrl: string; refreshToken: string }
export type SendEmailLoginRequestDto = { baseUrl: string; email: string | null; masterPasswordHash: string | null; authRequestId: string | null; authRequestAccessCode: string | null }
export type SessionResponseDto = { accessToken: string; refreshToken: string | null; expiresIn: number; tokenType: string; scope: string | null; key: string | null; privateKey: string | null; kdf: number | null; kdfIterations: number | null; kdfMemory: number | null; kdfParallelism: number | null; twoFactorToken: string | null }
export type SyncCountsDto = { folders: number; collections: number; policies: number; ciphers: number; sends: number }
export type SyncNowRequestDto = { baseUrl: string; accessToken: string; excludeDomains: boolean | null }
export type SyncStateDto = "idle" | "running" | "succeeded" | "failed"
export type SyncStatusRequestDto = { baseUrl: string; accessToken: string }
export type SyncStatusResponseDto = { accountId: string; baseUrl: string | null; state: SyncStateDto; wsStatus: WsStatusDto; lastRevisionMs: string | null; lastSyncAtMs: string | null; lastError: string | null; counts: SyncCountsDto }
export type TwoFactorChallengeDto = { error: string | null; errorDescription: string | null; providers: string[]; providers2: Partial<{ [key in string]: TwoFactorProviderHintDto | null }> | null; masterPasswordPolicy: MasterPasswordPolicyDto | null }
export type TwoFactorProviderHintDto = { host: string | null; signature: string | null; authUrl: string | null; nfc: boolean | null; email: string | null; challenge: string | null; timeout: number | null; rpId: string | null; allowCredentials: WebauthnAllowCredentialDto[]; userVerification: string | null; extensions: WebauthnRequestExtensionsDto | null }
export type VaultSyncFailed = { accountId: string; code: string; message: string }
export type VaultSyncStarted = { accountId: string }
export type VaultSyncSucceeded = { accountId: string; status: SyncStatusResponseDto }
export type VerifyEmailTokenRequestDto = { baseUrl: string; userId: string; token: string }
export type WebauthnAllowCredentialDto = { type: string | null; id: string | null; transports: string[] }
export type WebauthnRequestExtensionsDto = { appid: string | null }
export type WsStatusDto = "unknown" | "connected" | "disconnected"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
